# Main backend application configuration:
# database connection, JWT settings, file storage paths and multipart upload limits.

spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/career_platform
spring.datasource.username=postgres
spring.datasource.password=0000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

file.upload-dir=uploads/resumes
file.contracts-dir=uploads/contracts
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#jwt.secret=your-super-secret-key-your-super-secret-key
jwt.secret=5Ietx0o52IWCH00MffvXRMt8uVBNzCtDsebRoo7bHl9
jwt.expiration=86400000